Repository inovex/scrumlr.io-landing-page, pull requests merged in 2023-09, with the labels that each got.

#19 USPs & Responsiveness
  public/assets/backgrounds/bg_heights_dark.svg
  public/assets/backgrounds/bg_heights_light.svg
  public/assets/icons/icon-plus.svg
  public/assets/icons/icon_how-can-it-be-used_dark.svg
  public/assets/icons/icon_how-can-it-be-used_light.svg
  public/assets/icons/icon_what-is-it-about_dark.svg
  public/assets/icons/icon_what-is-it-about_light.svg
  public/assets/mobile/mobile_background_dark.svg
  public/assets/mobile/mobile_background_light.svg
  public/assets/mobile/mobile_dark.webp
  public/assets/mobile/mobile_dots.svg
  public/assets/mobile/mobile_light.webp
  public/assets/uniqueness/dots_dark_0.svg
  public/assets/uniqueness/dots_dark_1.svg
  public/assets/uniqueness/dots_dark_2.svg
  public/assets/uniqueness/dots_dark_3.svg
  public/assets/uniqueness/dots_light_0.svg
  public/assets/uniqueness/dots_light_1.svg
  public/assets/uniqueness/dots_light_2.svg
  public/assets/uniqueness/dots_light_3.svg
  public/assets/uniqueness/uniqueness_dark_0.webp
  public/assets/uniqueness/uniqueness_dark_0_mobile.webp
  public/assets/uniqueness/uniqueness_dark_1.webp
  public/assets/uniqueness/uniqueness_dark_1_mobile.webp
  public/assets/uniqueness/uniqueness_dark_2.webp
  public/assets/uniqueness/uniqueness_dark_2_mobile.webp
  public/assets/uniqueness/uniqueness_dark_3.webp
  public/assets/uniqueness/uniqueness_dark_3_mobile.webp
  public/assets/uniqueness/uniqueness_light_0.webp
  public/assets/uniqueness/uniqueness_light_0_mobile.webp
  public/assets/uniqueness/uniqueness_light_1.webp
  public/assets/uniqueness/uniqueness_light_1_mobile.webp
  public/assets/uniqueness/uniqueness_light_2.webp
  public/assets/uniqueness/uniqueness_light_2_mobile.webp
  public/assets/uniqueness/uniqueness_light_3.webp
  public/assets/uniqueness/uniqueness_light_3_mobile.webp
  src/components/Choices.scss
  src/components/Choices.tsx
  src/components/Footer/Footer.scss
  src/components/Footer/Footer.tsx
  src/components/Mobile.scss
  src/components/Mobile.tsx
  src/components/Navbar/Navbar.tsx
  src/components/Uniqueness.scss
  src/components/Uniqueness.tsx
  src/icons/ArrowRight.tsx
  src/layouts/Layout.astro
  src/pages/index.astro
Labels: Ready for Review

#38 About Us
  public/assets/about/background_dark.svg
  public/assets/about/background_details_dark.svg
  public/assets/about/background_details_dark_mobile.svg
  public/assets/about/background_details_light.svg
  public/assets/about/background_details_light_mobile.svg
  public/assets/about/background_light.svg
  public/assets/about/stan_dark.webp
  public/assets/about/stan_light.webp
  src/pages/index.astro
  src/views/AboutUs/AboutUs.scss
  src/views/AboutUs/AboutUs.tsx
Labels: Work in Progress, Ready for Review

#37 Target User (GIF)
  public/assets/images/target-user_dark.webm
  public/assets/images/target-user_light.webm
  src/pages/index.astro
  src/views/TargetUser/TargetUser.astro
  src/views/TargetUser/TargetUser.scss
Labels: Work in Progress
